Adicionar GitHub Actions para fazer executar linters, testes e deploy
DadosAbertosDeFeira/iac pull request #12
Opened 2021-01-18 15:29 UTC by felipefrizzo

#3

2021-01-18 15:47 UTC, edsoncelio commented
@felipefrizzo tem definida alguma dependência entre os workflows que vão ser executados? ex: primeiro lint, depois test e depois deploy.

2021-01-18 18:40 UTC, felipefrizzo commented
@edsoncelio então, eu resolvi por utilizar apenas um arquivo de workflow, para poder utilizar o `needs`, assim primeiro executaria o `molecule test` e os `linters`, para depois executar o playbook caso for a branch `main`

2021-01-18 22:45 UTC, edsoncelio commented
Foi apenas dúvida mesmo, quando vi ainda estava em workflows separados. Vou rever :)

2021-01-19 02:29 UTC, gomex requested changes
A PR como um todo ficou MUITO boa, parabéns! Obrigado pelo PR. Eu apenas fiz algumas sugestões de melhoria ;) Qualquer coisa, comenta ;)

2021-01-19 02:29 UTC, gomex commented on .ansible-lint
> +  - ./roles/iac-role-basica/
Tem como colocar uma linha em branco no fim?

2021-01-19 02:29 UTC, gomex commented on .ansible-lint
> +  - ./roles/iac-role-basica/
Não da pra excluir a pasta roles toda em um única linha não? (É uma dúvida mesmo).

2021-01-19 02:29 UTC, gomex commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Ao invés do latest, vamo escolher uma versão especifica, se tiver a 18.04, pode usar ela ;)

2021-01-19 02:29 UTC, gomex commented on .github/workflows/ci.yml
> +          ansible-galaxy install -r requirements.yml --roles-path ./roles
Não precisamos instalar as roles aqui, correto? Isso deixaria o CI mais rápido.

2021-01-19 02:29 UTC, gomex commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Ao invés do latest, vamo escolher uma versão especifica, se tiver a 18.04, pode usar ela ;)

2021-01-19 02:29 UTC, gomex commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
Ao invés do latest, vamo escolher uma versão especifica, se tiver a 18.04, pode usar ela ;)

2021-01-19 02:29 UTC, gomex commented on .github/workflows/ci.yml
> +          ansible-galaxy install -r requirements.yml --roles-path ./roles
Não precisa do "--roles-path ./roles" isso deve ser controlado pelo ansible.cfg. Precisamos evitar de configurar a mesma coisa em vários lugares.

2021-01-19 02:29 UTC, gomex commented on .github/workflows/ci.yml
> +          ansible-galaxy install -r requirements.yml --roles-path ./roles
Não precisa do "--roles-path ./roles" isso deve ser controlado pelo ansible.cfg. Precisamos evitar de configurar a mesma coisa em vários lugares.

2021-01-19 02:29 UTC, gomex commented on .yamllint
> +  roles/iac-role-basica/
Não precisa da segunda linha, correto? A primeira já resolve para qualquer role, eu acho.

2021-01-19 02:29 UTC, gomex commented on playbook.yml
> +    # swap_file_size_mb: '2048'
Aproveita e apaga esse comentário inteiro ;)

2021-01-19 11:42 UTC, felipefrizzo commented on .github/workflows/ci.yml
> +          ansible-galaxy install -r requirements.yml --roles-path ./roles
Então, nos testes que eu fiz ele retorna o seguinte erro:
```CRITICAL Couldn't parse task at playbook.yml:26 (couldn't resolve module/action 'dokku_app'. This often indicates a misspelling, missing collection, or incorrect module path.)
{ 'dokku_app': { '__file__': 'playbook.yml',
                 '__line__': 29,
                 'app': 'mariaquiteria.gomex.me'},
  'name': 'create app'}```

Quando instala as roles ele executa corretamente o linter

2021-01-19 14:44 UTC, gomex commented on .github/workflows/ci.yml
> +          ansible-galaxy install -r requirements.yml --roles-path ./roles
Ahhh! Verdade, ignora então ;) Obrigado pela explicação.

2021-01-19 14:46 UTC, gomex approved these changes
Me parece perfeito agora! Mergeado :)

2021-01-19 14:46 UTC, merged