Passos opcionais no prepare e chamada ao playbook no converge
DadosAbertosDeFeira/iac pull request #27
Opened 2021-02-11 15:24 UTC by francilioaraujo

Coloquei na configuração a chamada ao converge ao invés da chamada
direta ao playbook.
Adicionei um arquivo prepare para gerar a configuração do driver de
armazenamento do docker

2021-02-11 15:39 UTC, francilioaraujo commented
Vou alterar a parte da configuração do docker para passar no lint e modificar as chamadas aos módulos para aderir à versão 2.10 do ansible

2021-02-12 17:35 UTC, gomex commented
@francilioaraujo vc precisa retirar essa etapa do CI então: https://github.com/DadosAbertosDeFeira/iac/blob/2bac2fd2fba83f27047bba11fb8b727812386fed/.github/workflows/ci.yml#L45

2021-02-12 17:36 UTC, gomex requested changes
Por favor modifique isso ^

2021-02-12 19:25 UTC, gomex approved these changes
Ta lindo! Obrigado @francilioaraujo

2021-02-12 19:26 UTC, merged