adicionando configuração ao newrelic infra para coletar logs.
DadosAbertosDeFeira/iac pull request #59
Opened 2021-06-21 01:17 UTC by Rehzende

2021-06-21 11:26 UTC, gomex requested changes

2021-06-21 11:26 UTC, gomex commented on config_files/logging.yml
> +
Aqui na linha 17 e 20 possivelmente tem um espaço em branco desnecessário. Quebrou no lint.

2021-07-04 17:38 UTC, somatorio commented
```
(.venv) [somatorio@soma-pc mentoria-iac]$ molecule test
CRITICAL 'molecule/default/molecule.yml' glob failed.  Exiting.
```

:(

2021-07-11 18:29 UTC, merged

2021-07-11 18:29 UTC, gomex commented
LGTM