Versão do sshcommand e documentação
DadosAbertosDeFeira/iac pull request #6
Opened 2021-01-04 15:25 UTC by francilioaraujo

2021-01-06 09:47 UTC, anapaulagomes approved these changes
Obrigada pela contribuição, @francilioaraujo!

2021-01-06 09:47 UTC, anapaulagomes commented on README.md
> +Primeiro é necessário instalar as roles necessárias com o comando
```suggestion
Primeiro é necessário instalar as roles necessárias com o comando:
```

2021-01-06 09:49 UTC, anapaulagomes commented
O @gomex deve fazer a revisão final! 👍🏽

2021-01-07 15:50 UTC, gomex commented on README.md
> +Primeiro é necessário instalar as roles necessárias com o comando
Eu concordo com esse pedido de mudança aqui.

2021-01-07 15:50 UTC, gomex requested changes
A única mudança seria o que @anapaulagomes sugeriu mesmo.

2021-01-07 17:44 UTC, anapaulagomes commented
Valeu, @francilioaraujo! 🎉

2021-01-07 17:45 UTC, merged

2021-01-07 17:45 UTC, francilioaraujo reviewed
Aprovei as mudanças sugeridas pela @anapaulagomes