Ajuste para utilizar o Molecule
DadosAbertosDeFeira/iac pull request #8
Opened 2021-01-05 16:43 UTC by selmison

Propósitos dessa PR:
- habilita o Molecule para faciliar o processo de desenvolvimento e teste das roles ansible. 
- cria a role `setting-server` responsável pelas configurações mínimas do servidor.
-  Desabilita a role geerlingguy.swap, devido a um erro gerado quando usando a imagem docker geerlingguy/docker-ubuntu1804-ansible
- Fixa a versão do sshcommand para 0.12.0 pelas mesmas razões da PR #6 e da issue [#93](https://github.com/dokku/ansible-dokku/issues/93#issue-778427309)
- Depois de alguns testes e vendo a documentação em https://github.com/dokku/dokku-letsencrypt que diz: `Your app must already be deployed and accessible over the internet (i.e. in the browser) in order to add letsencrypt to your app.`, me parece que o certificado SSL só será gerado pelo Letsencrypt quando a aplicação foi deployada e já está acessível pela internet. Entendo, então, que a config do SSL sugerido na issue #1 deve ser o último passo.

2021-01-05 19:03 UTC, anapaulagomes requested changes
Muito obrigada pela contribuição, @selmison! Fiz alguns comentários de melhorias. Você pode, por favor, adicionar uma descrição ao PR? Ele resolve alguma das _issues_ que temos ou é algo novo?
Esse repositório ainda não tem um mas, por enquanto, você pode se basear no [guia de contribuição do nosso backend](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/main/CONTRIBUTING.md).

2021-01-05 19:03 UTC, anapaulagomes commented on README.md
> +## Development:
```suggestion
## Desenvolvimento
```

Tentamos sempre deixar todas as comunicações em português para facilitar a comunicação no projeto.

2021-01-05 19:03 UTC, anapaulagomes commented on README.md
> +### Prereqs:
```suggestion
### Requisitos
```

2021-01-05 19:03 UTC, anapaulagomes commented on README.md
> +    $ python3 -m virtualenv .venv
Pode usar também o `venv` padrão do Python: `python -v venv .venv`

2021-01-05 19:03 UTC, anapaulagomes commented on README.md
> +    $ pip install "molecule[docker,lint"
Aqui parece ter um erro de sintaxe: 
```suggestion
    $ pip install "molecule[docker,lint]"
```

2021-01-05 19:03 UTC, anapaulagomes commented on roles/setting-server/.travis.yml
> +python: "2.7"
Pode mudar pro Python 3? Python 2 não é mais mantido e tentamos trabalhar com as linguagens e bibliotecas atuais.

2021-01-05 19:03 UTC, anapaulagomes commented on README.md
> +### Prereqs:
Tem outras palavras mas vou deixar pra ti essa tarefa :)

2021-01-06 00:25 UTC, selmison commented on roles/setting-server/.travis.yml
> +python: "2.7"
Atualizado...

2021-01-06 00:27 UTC, selmison commented on README.md
> +    $ python3 -m virtualenv .venv
Atualizado...

2021-01-06 00:28 UTC, selmison commented
> Muito obrigada pela contribuição, @selmison! Fiz alguns comentários de melhorias. Você pode, por favor, adicionar uma descrição ao PR? Ele resolve alguma das _issues_ que temos ou é algo novo?
> Esse repositório ainda não tem um mas, por enquanto, você pode se basear no [guia de contribuição do nosso backend](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/main/CONTRIBUTING.md).

Olá, @anapaulagomes, fiz as alterações sugeridas...

2021-01-06 09:46 UTC, anapaulagomes requested changes
Obrigada pelas correções, @selmison! Espero que eu não esteja sendo muito _picky_. 😅 
O @gomex deve revisar a parte do Ansible em si (eu não manjo nada). Só tô aqui pra garantir que iniciantes ou não, falantes de inglês ou não, tenham uma boa experiência com o projeto. Valeu!

2021-01-06 09:46 UTC, anapaulagomes commented on roles/setting-server/README.md
> +A brief description of the role goes here.
Continua em inglês esse README aqui 😅

2021-01-06 09:46 UTC, anapaulagomes commented on roles/setting-server/meta/main.yml
> +  # Choose a valid license ID from https://spdx.org - some suggested licenses:
Podemos apagar esse tipo de comentário? Parecem ser de configurações que não vamos utilizar

2021-01-06 09:46 UTC, anapaulagomes commented on roles/setting-server/meta/main.yml
> +  company: your company (optional)
Devemos preencher essa seção com as informações do projeto, não?

2021-01-06 09:46 UTC, anapaulagomes commented on roles/setting-server/molecule/default/converge.yml
> +    - name: Update apt cache
```suggestion
    - name: Atualiza apt cache
```

2021-01-06 09:46 UTC, anapaulagomes commented on roles/setting-server/molecule/default/verify.yml
> +# This is an example playbook to execute Ansible tests.
⚠️

2021-01-06 09:46 UTC, anapaulagomes commented on roles/setting-server/tasks/main.yml
> +# tasks file for setting-server
⚠️

2021-01-06 09:46 UTC, anapaulagomes commented on README.md
> +
Podemos apagar essa linha extra, não?

2021-01-06 09:46 UTC, anapaulagomes commented on .gitignore
> +.venv/
Podemos adicionar uma linha aqui (vai evitar essa bolinha vermelha e indicar corretamente o fim do arquivo).

2021-01-07 15:55 UTC, gomex commented
A ideia é sensacional, mas eu faria em um outro repositório, que tal? Podemos colocar um Makefile aqui só apontando para baixar a role pra fazer o teste ;)

2021-01-08 16:26 UTC, selmison reviewed
> A ideia é sensacional, mas eu faria em um outro repositório, que tal? Podemos colocar um Makefile aqui só apontando para baixar a role pra fazer o teste ;)

Por mim, tudo bem

2021-01-08 16:26 UTC, selmison commented on roles/setting-server/README.md
> +A brief description of the role goes here.
Muitos desses arquivos são gerados automaticamente pela ferramenta Molecule. Esse arquivo Readme.md, por exemplo, foi totalmente gerado pela ferramenta e por ora até pode ser deleteado se desejarem

2021-01-08 16:53 UTC, anapaulagomes commented
Pode ficar a vontade pra deletar o que você acha que não vai precisar, @selmison! Sugestões para o nome do repositório? Só falar que eu crio aqui. :)

2021-01-08 19:54 UTC, selmison reviewed
> Pode ficar a vontade pra deletar o que você acha que não vai precisar, @selmison! Sugestões para o nome do repositório? Só falar que eu crio aqui. :)

Não sou bom em nomes rs... pensei em iac-roles

2021-01-09 06:53 UTC, anapaulagomes commented on roles/setting-server/README.md
> +A brief description of the role goes here.
Pode deletar então?

2021-01-09 06:54 UTC, anapaulagomes commented
Feito @selmison: https://github.com/DadosAbertosDeFeira/iac-roles :)

2021-01-10 03:55 UTC, gomex commented
Obrigado pelo PR @selmison! Eu ja aceitei e aproveitei pra organizar as coisas depois do merge. Olha lá como ficou:

2021-01-10 03:55 UTC, closed without merging